name: bb_utils-CI
run-name: ${{ github.actor }} is validating the bb_utils repo
on:
  push:
    paths:
      - bb_utils/**
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - run: cd /home/runner/work/bb_utils/bb_utils
      - name: setup env vars
        run: make build-gha
      - name: setup conda env and activate
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: bb_utils
          environment-file: bb_utils/environment.yml
          auto-activate-base: false
      - name: run tests
        run: make test-gha
        env:
          BB_PATHS: ${{ env.BB_PATHS }}
          PYTHONPATH: ${{ env.PYTHONPATH }}
